services:
  gdq-watch-party:
    image: ghcr.io/loldencode/gdq-cal:latest
    restart: unless-stopped
    environment:
      GDQ_EVENT_ID: "66"
      DATA_FILE: /data/watch-plans.json
      ADMIN_KEY: change-me
    ports:
      - "18080:3000"
    volumes:
      - gdq_data:/data
    networks:
      - porty_default
    labels:
      - traefik.enable=true
      - traefik.docker.network=porty_default
      - traefik.http.routers.gdq-watch-party.rule=Host(`gdq.lolden.xyz`)
      - traefik.http.routers.gdq-watch-party.entrypoints=https
      - traefik.http.routers.gdq-watch-party.tls=true
      - traefik.http.routers.gdq-watch-party.service=gdq-watch-party
      - traefik.http.services.gdq-watch-party.loadbalancer.server.port=3000
      - traefik.http.services.gdq-watch-party.loadbalancer.server.scheme=http

networks:
  porty_default:
    external: true

volumes:
  gdq_data:
